name: Push RaysGitOpsDemo.Chassis.Caching

on:
  push:
    branches:
        - main
    paths:
        - .github/workflows/publish-caching.yml
        - src/RaysGitOpsDemo.Chassis.Caching/**
jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 6.0.x
            
            - name: Setup NuGet Source
              run: dotnet nuget add source \
                --username ${{ secrets.GHP_USER }} \
                --password ${{ secrets.GHP_PASSWORD }} \
                --store-password-in-clear-text \
                --name ghp

            - name: Pack
              run: dotnet pack src/RaysGitOpsDemo.Chassis.Common -c Release -o packages

            - name: Push
              run: dotnet nuget push packages/RaysGitOpsDemo.Chassis.Caching.nupkg \
                -s ghp \
                -k "${{ secrets.GHP_USER }}:${{ secrets.GHP_PASSWORD }}" \
                --skip-duplicate