name: Push RaysGitOpsDemo.Chassis

on:
  push:
    branches:
        - main
    paths:
        - .github/workflows/publish-chassis.yml
        - src/RaysGitOpsDemo.Chassis/**
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 6.0.x

            - name: Pack
              run: dotnet pack src/RaysGitOpsDemo.Chassis.Common -c Release -o packages

            - name: Push
              run: dotnet nuget push packages/RaysGitOpsDemo.Chassis.nupkg \
                -k "${{ secrets.GHP_USER }}:${{ secrets.GHP_PASSWORD }}" \
                --skip-duplicate
